[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
    madhephaestus/ESP32Encoder@^0.12.0
    hideakitai/MPU9250@^0.4.8
    ; https://github.com/eclipse-zenoh/zenoh-pico.git#1.0.0  Te lo descargas una vez y lo pones en la carpeta "lib" del proyecto, para quitar el freeRTOS externo y que se compile con el del ESP32
    https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary.git

build_flags = 
    # --- Configuración Base de Zenoh-pico ---
    -D ZENOH_COMPILER_GCC
    -D ZENOH_ARDUINO_ESP32
    -D ZP_PLATFORM=arduino_esp32
    -D ZP_NET=bsd
    
    # --- Ajustes de Memoria y Funcionalidades ---
    -D Z_FEATURE_SUBSCRIPTION=1
    -D CORE_DEBUG_LEVEL=0 ; Bajamos el debug para ahorrar RAM

